export { default as FormInput } from './FormInput';
export { default as SubmitBtn } from './SubmitBtn';
export { default as Navbar } from './Navbar';
export { default as Header } from './Header';
export { default as NavLinks } from './NavLinks';
export { default as Hero } from './Hero';
export { default as ErrorElement } from './ErrorElement';
export { default as ProductsGrid } from './ProductsGrid';
export { default as SectionTitle } from './SectionTitle';
export { default as FeaturedProducts } from './FeaturedProducts';
// export { default as Footer } from './Footer';
// export { default as Cart } from './Cart';
// export { default as Orders } from './Orders';
// export { default as Register } from './Register';
// export { default as Login } from './Login';
// export { default as Checkout } from './Checkout';
// export { default as SingleProduct } from './SingleProduct';
// export { default as About } from './About';
// export { default as Landing } from './Landing';
// export { default as HomeLayout } from './HomeLayout';
// export { default as Error } from './Error';